# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8acd2cf0d033bbc2c3507b041737ed85eb2a65e7810d99a99fab0e8ac275cffaca852ec86721f98f94c3a40e53be278b6be682a1ce50e1d3e4890cba4e020a

test:
  secret_key_base: 8c75a3fd963391040f06bc68bdff99c5f6240309da6d2a5d21f1f4e174161855ee151100f7769f516f5ecbf2491fb0f01cea33313488d124e2956c914d7ffbd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
